site_name: duykhanh471 tự học
site_description: Tôi học từ sách và Internet
site_author: duykhanh471  
site_url: https://duy103zxc.github.io/bnt2
repo_name: Tạo PR tại đây
repo_url: https://github.com/duy103zxc/bnt2

nav:
  - 'Trang chủ': 'index.md'
  - 'Đọc sách':
    - 'Nguyễn Duy Cần': 
      - 'Trang chủ': 'hoc-hoi/hoc-gia/thu-giang/index.md'
    - 'Nguyễn Hiến Lê': 
      - 'Trang chủ': 'hoc-hoi/hoc-gia/nguyen-hien-le/index.md'
    - 'Sách khác':
      - 'Nghiện mềm': 'hoc-hoi/sach/index.md'
      - 'Nghiện mềm': 'hoc-hoi/sach/nghien-mem.md'
      - 'Rational Recovery': 'hoc-hoi/sach/rational-recovery.md'
      - 'Chạy trốn hiện đại': 'hoc-hoi/sach/chay-tron-hien-dai.md'
  - 'Du lịch':
    - 'Hà Nội':
      - 'Mở đầu': 'ban-than/du-lich/ha-noi/index.md'
      - 'Sóc Sơn':
        - 'Đền Sóc': 'ban-than/du-lich/ha-noi/soc-son/den-soc/index.md'
        - 'Đền Phủ Thành Chương': 'ban-than/du-lich/ha-noi/soc-son/den-phu-thanh-chuong/index.md'
      - 'Hoài Đức':
        - 'Làng Dương Liễu': 'ban-than/du-lich/ha-noi/hoai-duc/duong-lieu/index.md'
      - 'Chương Mỹ':
        - 'Chùa Trầm': 'ban-than/du-lich/ha-noi/chuong-my/chua-tram/index.md'
      - 'Gia Lâm': 'ban-than/du-lich/ha-noi/gia-lam/index.md'
      - 'Long Biên': 'ban-than/du-lich/ha-noi/long-bien/index.md'
      - 'Sơn Tây':
        - 'Làng cổ Đường Lâm': 'ban-than/du-lich/ha-noi/son-tay/lang-co-duong-lam/index.md'
      - 'Trung tâm thành phố': 
        - 'Trang chủ': 'ban-than/du-lich/ha-noi/trung-tam-thanh-pho/index.md'
        - 'Văn Miếu': 'ban-than/du-lich/ha-noi/trung-tam-thanh-pho/van-mieu/index.md'
        - 'Bảo tàng Hà Nội': 'ban-than/du-lich/ha-noi/trung-tam-thanh-pho/bao-tang-ha-noi/index.md'
        - 'Không biết chỗ nào': 'ban-than/du-lich/ha-noi/trung-tam-thanh-pho/khong-nho-o-dau/index.md'
    - 'Bắc Ninh':
      - 'Trang chủ': 'ban-than/du-lich/bac-ninh/index.md'
      - 'Chùa Phật Tích': 'ban-than/du-lich/bac-ninh/chua-phat-tich/index.md'
      - 'Chợ Từ Sơn': 'ban-than/du-lich/bac-ninh/cho-tu-son/index.md'
      - 'Chùa Lý Thái Tổ': 'ban-than/du-lich/bac-ninh/chua-ly-thai-to/index.md'
    - 'Bắc Giang':
      - 'ban-than/du-lich/bac-giang/index.md'
      - 'Đền Xương Giang': 'ban-than/du-lich/bac-giang/den-xuong-giang/index.md'
      - 'Làng Thổ Hà': 'ban-than/du-lich/bac-giang/lang-tho-ha/index.md'
  - 'Bài viết':
    - 'Nhận thức, nhận ngủ': 'ban-than/blog/nhan-thuc-nhan-ngu.md'
    - 'Dùng voz khá thích': 'ban-than/blog/dung-voz-kha-thich.md'
    - 'Tôi viết sách': 'ban-than/blog/toi-viet-sach.md'
  - 'Học ngoại ngữ':
    - 'Tiếng Anh': 
      - 'Định hướng': 'tieng-anh/index.md'   
      - 'Ngữ pháp': 'tieng-anh/ngu-phap.md'
    - 'Tiếng Nhật':
      - 'N6': 'tieng-nhat/n6.md'
      - 'N5': 'tieng-nhat/n5.md'
      - 'N4': 'tieng-nhat/n4.md'
      - 'N3': 'tieng-nhat/n3.md'
      - 'N2': 'tieng-nhat/n2.md'
      - 'N1': 'tieng-nhat/n1.md'
  - 'Tác phẩm':
    - 'Văn học': 'tac-pham/sach.md'
    - 'Anime': 'tac-pham/anime.md'
    - 'Manga': 'tac-pham/manga.md'
    - 'Phim': 'tac-pham/phim.md'
  - 'Thông tin thêm':
    - 'Về cái trang này': 'about.md'



theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.share
    - toc.follow
    - search.suggest
    - search.highlight
  name: material

plugins:
  - search
  - open-in-new-tab

extra:
  generator: false